/* CLASSCO AI public support widget. API keys never belong in this file. */
(() => {
'use strict';
const API_ENDPOINT = 'https://YOUR-WORKER-NAME.YOUR-SUBDOMAIN.workers.dev';
const css = `
#classco-ai-launcher{position:fixed;right:24px;bottom:96px;z-index:9990;display:flex;align-items:center;gap:10px;padding:12px 16px;border:1px solid #d8b4fe88;border-radius:999px;background:linear-gradient(120deg,#7e22ce,#c026d3);color:#fff;font:800 12px Inter,Arial,sans-serif;box-shadow:0 8px 35px #a855f755;cursor:pointer;transition:transform .2s}
#classco-ai-launcher:hover{transform:translateY(-3px)}
#classco-ai-launcher .ec-ai-orb{display:grid;place-items:center;width:27px;height:27px;border-radius:50%;background:#ffffff24;font-size:16px}
#classco-ai-panel{position:fixed;right:24px;bottom:158px;z-index:9991;display:none;flex-direction:column;width:min(390px,calc(100vw - 28px));height:min(590px,calc(100dvh - 190px));min-height:380px;overflow:hidden;border:1px solid #a855f799;border-radius:20px;background:radial-gradient(ellipse at 100% 0%,#3b1764 0,transparent 45%),#100b1b;color:#f7f3ff;font-family:Inter,Arial,sans-serif;box-shadow:0 24px 80px #000b}
#classco-ai-panel.ec-open{display:flex;animation:ec-ai-enter .2s ease-out}
@keyframes ec-ai-enter{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:translateY(0)}}
.ec-ai-head{display:flex;align-items:center;gap:11px;padding:15px;border-bottom:1px solid #ffffff15;background:#120c20dd}
.ec-ai-avatar{display:grid;place-items:center;flex:0 0 40px;height:40px;border:1px solid #e9d5ff66;border-radius:14px;background:linear-gradient(145deg,#9333ea,#c026d3);font-size:20px}
.ec-ai-head-copy{min-width:0;flex:1}.ec-ai-head-copy strong{display:block;font-size:13px}.ec-ai-head-copy small{display:flex;align-items:center;gap:6px;margin-top:5px;color:#c4b5fd;font-size:10px}.ec-ai-online{width:6px;height:6px;border-radius:50%;background:#34d399}
.ec-ai-head button{width:30px;height:30px;border:1px solid #ffffff1f;border-radius:9px;background:#ffffff0a;color:#ddd0f3;font-size:19px;cursor:pointer}
.ec-ai-content{flex:1;min-height:0;overflow-y:auto;padding:15px;scroll-behavior:smooth}
.ec-ai-welcome{margin:4px 0 14px;padding:14px;border:1px solid #a855f744;border-radius:14px;background:linear-gradient(140deg,#241238,#171024)}
.ec-ai-welcome .eyeline{color:#d8b4fe;font-size:9px;font-weight:900;letter-spacing:1.6px}.ec-ai-welcome h3{margin:7px 0;font-size:17px;line-height:1.35}.ec-ai-welcome p{margin:0;color:#b9abc9;font-size:11px;line-height:1.65}
.ec-ai-chips{display:flex;flex-wrap:wrap;gap:7px;margin:0 0 14px}.ec-ai-chip{padding:8px 10px;border:1px solid #c084fc44;border-radius:999px;background:#1a1029;color:#e9d5ff;font:700 10px Inter,Arial,sans-serif;cursor:pointer}.ec-ai-chip:hover{border-color:#c084fc}
.ec-ai-message{display:flex;flex-direction:column;align-items:flex-start;margin:11px 0;gap:4px}.ec-ai-message.user{align-items:flex-end}.ec-ai-bubble{max-width:92%;padding:10px 12px;border:1px solid #ffffff14;border-radius:13px 13px 13px 4px;background:#1c1429;color:#eee7f8;font-size:12px;line-height:1.65;white-space:pre-wrap;overflow-wrap:anywhere}.ec-ai-message.user .ec-ai-bubble{border-color:#a855f766;border-radius:13px 13px 4px 13px;background:linear-gradient(120deg,#6522a5,#8b28a9);color:white}.ec-ai-time{padding:0 3px;color:#8f82a5;font-size:9px}
.ec-ai-typing{display:flex;align-items:center;gap:4px;padding:12px 14px}.ec-ai-typing i{width:5px;height:5px;border-radius:50%;background:#d8b4fe;animation:ec-ai-dot .9s infinite alternate}.ec-ai-typing i:nth-child(2){animation-delay:.2s}.ec-ai-typing i:nth-child(3){animation-delay:.4s}@keyframes ec-ai-dot{to{opacity:.25;transform:translateY(-3px)}}
.ec-ai-error{margin:9px 0;padding:9px 11px;border:1px solid #fb718544;border-radius:10px;background:#88133722;color:#fecdd3;font-size:10px;line-height:1.6}
.ec-ai-footnote{padding:0 14px 9px;color:#8f82a5;font-size:9px;line-height:1.5}
.ec-ai-form{display:flex;align-items:flex-end;gap:8px;padding:11px;border-top:1px solid #ffffff16;background:#0e0917}.ec-ai-form textarea{flex:1;min-width:0;max-height:100px;min-height:42px;resize:none;padding:12px;border:1px solid #ffffff20;border-radius:12px;outline:none;background:#191124;color:#fff;font:12px/1.5 Inter,Arial,sans-serif}.ec-ai-form textarea:focus{border-color:#a855f7}.ec-ai-form button{width:42px;height:42px;flex:0 0 42px;border:0;border-radius:12px;background:linear-gradient(140deg,#9333ea,#c026d3);color:white;font-size:18px;cursor:pointer}.ec-ai-form button:disabled{opacity:.45;cursor:wait}.ec-ai-form textarea::placeholder{color:#8f82a5}
@media(max-width:620px){#classco-ai-launcher{right:14px;bottom:88px;padding:10px 13px}#classco-ai-panel{right:8px;bottom:142px;width:calc(100vw - 16px);height:min(620px,calc(100dvh - 165px));min-height:340px}}
@media(prefers-reduced-motion:reduce){#classco-ai-panel.ec-open{animation:none}.ec-ai-typing i{animation:none}}
`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const make=(tag,cls,text)=>{const el=document.createElement(tag);if(cls)el.className=cls;if(text!==undefined)el.textContent=text;return el;};
const launcher=make('button','','');launcher.id='classco-ai-launcher';launcher.type='button';launcher.setAttribute('aria-expanded','false');launcher.setAttribute('aria-controls','classco-ai-panel');launcher.innerHTML='<span class="ec-ai-orb" aria-hidden="true">✦</span><span>CLASSCO AI <small style="display:block;margin-top:2px;font-size:9px;font-weight:600;opacity:.85">Müşteri desteği</small></span>';
const panel=make('section');panel.id='classco-ai-panel';panel.setAttribute('role','dialog');panel.setAttribute('aria-label','CLASSCO AI müşteri hizmetleri');
const head=make('div','ec-ai-head');head.append(make('div','ec-ai-avatar','✦'));const headCopy=make('div','ec-ai-head-copy');headCopy.append(make('strong','','CLASSCO AI'));const status=make('small');status.append(make('i','ec-ai-online'),document.createTextNode(' Yapay zekâ destek asistanı'));headCopy.append(status);const close=make('button','','×');close.type='button';close.setAttribute('aria-label','Pencereyi kapat');head.append(headCopy,close);
const content=make('div','ec-ai-content');content.setAttribute('aria-live','polite');const welcome=make('div','ec-ai-welcome');welcome.append(make('div','eyeline','EL CLASSCO DESTEK MERKEZİ'),make('h3','','Selam! Sana nasıl yardımcı olabilirim?'),make('p','','Oyun bağlantıları, site kullanımı veya teknik bir sorun mu? Yaz, birlikte çözelim.'));
const chips=make('div','ec-ai-chips');['İndirme bağlantısı çalışmıyor','Oyun kurulumunda yardım','Siteyle ilgili bir sorum var'].forEach(label=>{const b=make('button','ec-ai-chip',label);b.type='button';b.addEventListener('click',()=>{input.value=label;form.requestSubmit();});chips.appendChild(b);});content.append(welcome,chips);
const foot=make('div','ec-ai-footnote','Yapay zekâ yanıtları hatalı olabilir. Şifre veya ödeme bilgisi paylaşma.');const form=make('form','ec-ai-form');const input=make('textarea');input.rows=1;input.maxLength=1200;input.placeholder='Sorununu buraya yaz…';input.setAttribute('aria-label','Mesajın');input.required=true;const send=make('button','','➤');send.type='submit';send.setAttribute('aria-label','Mesajı gönder');form.append(input,send);panel.append(head,content,foot,form);document.body.append(launcher,panel);
const history=[];let pending=false,lastSentAt=0;
const setOpen=open=>{panel.classList.toggle('ec-open',open);launcher.setAttribute('aria-expanded',String(open));if(open)setTimeout(()=>input.focus(),80);};
launcher.addEventListener('click',()=>setOpen(!panel.classList.contains('ec-open')));document.querySelectorAll('[data-classco-ai-open]').forEach(el=>el.addEventListener('click',()=>setOpen(true)));close.addEventListener('click',()=>setOpen(false));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&panel.classList.contains('ec-open'))setOpen(false);});
function addMessage(role,text){const row=make('div','ec-ai-message '+role);row.append(make('div','ec-ai-bubble',text),make('span','ec-ai-time',new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit'})));content.appendChild(row);content.scrollTop=content.scrollHeight;}
function errorMessage(text){content.appendChild(make('div','ec-ai-error',text));content.scrollTop=content.scrollHeight;}
function typing(){const row=make('div','ec-ai-message');row.id='ec-ai-typing';const dots=make('div','ec-ai-bubble ec-ai-typing');for(let i=0;i<3;i++)dots.appendChild(make('i'));row.appendChild(dots);content.appendChild(row);content.scrollTop=content.scrollHeight;}
form.addEventListener('submit',async e=>{e.preventDefault();const text=input.value.trim();if(!text||pending)return;if(text.length>1200){errorMessage('Mesaj en fazla 1200 karakter olabilir.');return;}if(Date.now()-lastSentAt<1200){errorMessage('Bir saniye bekleyip tekrar dene.');return;}lastSentAt=Date.now();if(!API_ENDPOINT.startsWith('https://')||API_ENDPOINT.includes('YOUR-WORKER-NAME')){errorMessage('CLASSCO AI bağlantısı henüz kurulmamış. CLASSCO-AI-SETUP.md dosyasındaki Worker kurulumunu tamamlamak gerekiyor.');return;}
pending=true;send.disabled=true;input.disabled=true;addMessage('user',text);history.push({role:'user',content:text});input.value='';input.style.height='auto';typing();
try{const response=await fetch(API_ENDPOINT.replace(/\/$/,'')+'/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:history.slice(-8)})});const data=await response.json().catch(()=>({}));if(!response.ok){if(response.status===429)throw new Error(data.error||'Çok fazla mesaj gönderildi. Biraz bekleyip tekrar dene.');if(response.status===503)throw new Error('Yapay zekâ servisi henüz yapılandırılmamış.');throw new Error(data.error||'Yanıt alınamadı. Biraz sonra tekrar dene.');}const reply=String(data.reply||'').trim();if(!reply)throw new Error('Asistan boş yanıt döndürdü. Tekrar deneyebilir misin?');history.push({role:'assistant',content:reply});addMessage('assistant',reply);}
catch(err){if(history.at(-1)?.role==='user')history.pop();errorMessage(err.message||'Bağlantı kurulamadı. İnternetini kontrol edip tekrar dene.');}
finally{document.getElementById('ec-ai-typing')?.remove();pending=false;send.disabled=false;input.disabled=false;input.focus();}
});
input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,100)+'px';});
})();