-- EL CLASSCO: import the existing index.html catalog into Supabase.
-- Safe to run repeatedly: existing game names are not duplicated.
-- Source catalog currently contains 26 games.
insert into public.games
  (name, category, download_url, cover_url, system_requirements, description, tags, is_cheat)
select seed.name, seed.category, seed.download_url, seed.cover_url,
       seed.system_requirements, seed.description, seed.tags, seed.is_cheat
from (values
  ('CS2 Özel Mod / Hilesi', 'CS2 / Hile', 'https://discord.gg/rJBhRxVuY', 'https://cdn.cloudflare.steamstatic.com/steam/apps/730/header.jpg', '• İşletim Sistemi: Windows 10 64-Bit<br>• İşlemci: Intel Core i5 7500 / AMD Ryzen 5 1600<br>• Bellek: 8 GB RAM<br>• Ekran Kartı: GTX 1050 Ti / RX 570<br>• Depolama: 85 GB kullanılabilir alan', NULL, ARRAY['VİDEO ÖNİZLEME ⚡']::text[], true),
  ('Euro Truck Simulator 2', 'Simülasyon / Araba', 'https://megaup.net/9b7c4b29ca80e82f4fb4c2f636ecbd95/Euro.Truck.Simulator.2.v1.60.1.0s.rar', 'https://cdn.cloudflare.steamstatic.com/steam/apps/227300/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel Core i5-6400 / AMD Ryzen 3 1200<br>• Bellek: 8 GB RAM<br>• Ekran Kartı: GTX 660 / Radeon RX 460<br>• Depolama: 25 GB kullanılabilir alan', NULL, ARRAY['Favori 🚚']::text[], false),
  ('Cyberpunk 2077', 'Açık Dünya / RPG', 'https://gofile.io/d/1EMT54', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1091500/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel Core i7-6700 / AMD Ryzen 5 1600<br>• Bellek: 12 GB RAM<br>• Ekran Kartı: GTX 1060 6GB / RX 580<br>• Depolama: 70 GB SSD', NULL, ARRAY['Çok Popüler 🔥']::text[], false),
  ('Grand Theft Auto V', 'Açık Dünya / Aksiyon', 'https://transfer.it/t/qXwxErwn1LaY', 'https://cdn.cloudflare.steamstatic.com/steam/apps/271590/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel Core i5 3470 / AMD X8 FX-8350<br>• Bellek: 8 GB RAM<br>• Ekran Kartı: NVIDIA GTX 660 2GB / AMD HD 7870<br>• Depolama: 110 GB alan', NULL, ARRAY['Efsane 👑']::text[], false),
  ('God of War', 'Aksiyon / Hikâye', 'https://gofile.io/d/OUbvV2', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1593500/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel i5-2500k / AMD Ryzen 3 1200<br>• Bellek: 8 GB RAM<br>• Ekran Kartı: NVIDIA GTX 960 (4 GB) / AMD R9 290X<br>• Depolama: 70 GB SSD', NULL, ARRAY['Şaheser ⚔️']::text[], false),
  ('Red Dead Redemption 2', 'Açık Dünya / Hikâye', 'https://gofile.io/d/pdRrzq', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel Core i7-4770K / AMD FX-9590<br>• Bellek: 12 GB RAM<br>• Ekran Kartı: NVIDIA GTX 1060 6GB / AMD RX 480<br>• Depolama: 150 GB alan', NULL, ARRAY['Şaheser 🤠']::text[], false),
  ('BeamNG.drive', 'Simülasyon / Araba', 'https://drive.usercontent.google.com/download?id=1cQkmx46H5tMu7-9gRIUmCUVdGKl7og53&authuser=0', 'https://cdn.cloudflare.steamstatic.com/steam/apps/284160/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel Core i5-4670 / AMD FX-8350<br>• Bellek: 16 GB RAM<br>• Ekran Kartı: GTX 970 / Radeon R9 290<br>• Depolama: 50 GB kullanılabilir alan', NULL, ARRAY['Fizik 🔥']::text[], false),
  ('Battlefield 1', 'FPS / Aksiyon', 'https://pixeldrain.com/u/vofoyM4i', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1238840/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel Core i5 6600K / AMD FX-6350<br>• Bellek: 8 GB RAM<br>• Ekran Kartı: GTX 660 2GB / HD 7850 2GB<br>• Depolama: 50 GB alan', NULL, ARRAY['Çok Popüler 🔥']::text[], false),
  ('Battlefield 5', 'FPS / Aksiyon', 'https://gofile.io/d/D7gmvc', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1238810/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel Core i5 6600K / AMD FX-8350<br>• Bellek: 12 GB RAM<br>• Ekran Kartı: NVIDIA GTX 1060 3GB / RX 580<br>• Depolama: 50 GB alan', NULL, ARRAY[]::text[], false),
  ('Assetto Corsa', 'Yarış / Simülasyon', 'https://www.mediafire.com/file/ojyxik0g3nrcb35/Assetto+Corsa.7z/file', 'https://cdn.cloudflare.steamstatic.com/steam/apps/244210/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: AMD Six-Core / Intel Quad-Core<br>• Bellek: 8 GB RAM<br>• Ekran Kartı: GTX 970 / Radeon R9 290<br>• Depolama: 30 GB alan', NULL, ARRAY['Simülasyon 🏎️']::text[], false),
  ('God of War Ragnarök', 'Aksiyon / Hikâye', 'https://gofile.io/d/4LbYNU', 'https://cdn.cloudflare.steamstatic.com/steam/apps/2322010/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel i5-8600 / AMD Ryzen 5 3600<br>• Bellek: 16 GB RAM<br>• Ekran Kartı: NVIDIA RTX 2060 Super / RX 5700<br>• Depolama: 190 GB SSD', NULL, ARRAY['Yeni ✨']::text[], false),
  ('Spider-Man 3', 'Aksiyon / Süper kahraman', 'https://bowfile.com/6sqi#popup1', 'https://m.media-amazon.com/images/M/MVBMTM3NTg3NDgwNV5BMl5BanBnXkFtZTcwNTI5NTM1MQ@@._V1_.jpg', '• İşletim Sistemi: Windows XP / 7 / 10<br>• İşlemci: Intel Pentium 4 2.8 GHz<br>• Bellek: 2 GB RAM<br>• Ekran Kartı: 256 MB DirectX 9.0c Uyumlu Kart<br>• Depolama: 6 GB alan', NULL, ARRAY['Nostalji 🕸️']::text[], false),
  ('Grand Theft Auto: San Andreas', 'Açık Dünya / Aksiyon', 'https://transfer.it/t/DfEDqj51VTwR', 'https://cdn.cloudflare.steamstatic.com/steam/apps/12120/header.jpg', '• İşletim Sistemi: Windows 7 / 10 / 11<br>• İşlemci: 1 GHz Pentium III / Athlon<br>• Bellek: 512 MB RAM<br>• Ekran Kartı: 64 MB DirectX 9 Uyumlu Kart<br>• Depolama: 4.7 GB alan', NULL, ARRAY['Düşük Sistem 💻']::text[], false),
  ('Hitman: World of Assassination', 'Gizlilik / Aksiyon', 'https://gofile.io/d/opbggB', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1659040/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel CPU Core i5-2500K / AMD Phenom II X4<br>• Bellek: 8 GB RAM<br>• Ekran Kartı: NVIDIA GTX 660 / Radeon HD 7870<br>• Depolama: 80 GB SSD', NULL, ARRAY[]::text[], false),
  ('PAYDAY 2', 'FPS / Aksiyon', 'https://gofile.io/d/tLhrfYoP', 'https://cdn.cloudflare.steamstatic.com/steam/apps/218620/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: 2 GHz Intel Quad Core Processor<br>• Bellek: 4 GB RAM<br>• Ekran Kartı: NVIDIA GeForce GTX 460 / Radeon HD 5850<br>• Depolama: 83 GB alan', NULL, ARRAY['Co-Op 🎭']::text[], false),
  ('Outlast 2', 'Korku', 'https://pixeldrain.com/u/UPTajG2H', 'https://cdn.cloudflare.steamstatic.com/steam/apps/414700/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel Core i3-530 / AMD Phenom II X4 965<br>• Bellek: 8 GB RAM<br>• Ekran Kartı: GTX 660 2GB / Radeon HD 7870<br>• Depolama: 30 GB alan', NULL, ARRAY['Korku 💀']::text[], false),
  ('İblis 3', 'Korku', 'https://www.mediafire.com/file/yzuuuwb7w8yekiy/iblis+3+(bkbtb+-+berkant).zip/file', 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?auto=format&fit=crop&w=600&q=80', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel i5 / AMD Ryzen 3<br>• Bellek: 8 GB RAM<br>• Ekran Kartı: GTX 1050 Ti<br>• Depolama: 10 GB alan', NULL, ARRAY['Yerli 🇹🇷']::text[], false),
  ('eFootball PES 2021', 'Spor / Futbol', 'https://drive.usercontent.google.com/download?id=1OoQsdHG_9MO8_LPdzFsxm2V4kGdrjlWk&export=download&authuser=0', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1259970/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel Core i5-3470 / AMD FX 4350<br>• Bellek: 8 GB RAM<br>• Ekran Kartı: GTX 670 / Radeon HD 7870<br>• Depolama: 40 GB alan', NULL, ARRAY[]::text[], false),
  ('Watch Dogs 2', 'Açık Dünya / Aksiyon', 'https://gofile.io/d/wW77bP', 'https://cdn.cloudflare.steamstatic.com/steam/apps/447040/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel Core i5 2400s / AMD FX 6120<br>• Bellek: 8 GB RAM<br>• Ekran Kartı: GTX 660 / Radeon HD 7870<br>• Depolama: 50 GB alan', NULL, ARRAY[]::text[], false),
  ('WWE 2K24', 'Spor / Güreş', 'https://datanodes.to/download', 'https://cdn.cloudflare.steamstatic.com/steam/apps/2315690/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel i5-4770 / AMD FX-8350<br>• Bellek: 16 GB RAM<br>• Ekran Kartı: GTX 1070 / Radeon RX 5700<br>• Depolama: 90 GB SSD', NULL, ARRAY['Yeni ✨']::text[], false),
  ('Car Dealership Simulator', 'Simülasyon / Araba', 'https://store.steampowered.com/search/?term=Car%20Dealership%20Simulator', 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=600&q=80', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel Core i5-2500K / AMD FX-6300<br>• Bellek: 8 GB RAM<br>• Ekran Kartı: GTX 960 / Radeon R9 280<br>• Depolama: 15 GB alan', NULL, ARRAY[]::text[], false),
  ('Car Service Together', 'Simülasyon / Araba', 'https://store.steampowered.com/search/?term=Car%20Service%20Together', 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=600&q=80', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel i5 6.Nesil<br>• Bellek: 8 GB RAM<br>• Ekran Kartı: GTX 1050 Ti<br>• Depolama: 10 GB alan', NULL, ARRAY[]::text[], false),
  ('Hello Neighbor 2', 'Korku / Gizem', 'https://gofile.io/d/BX8NB5', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1321680/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel i5 8400 / AMD Ryzen 5 2600<br>• Bellek: 8 GB RAM<br>• Ekran Kartı: GTX 1060 / Radeon RX 580<br>• Depolama: 20 GB alan', NULL, ARRAY[]::text[], false),
  ('Outlast', 'Korku', 'https://gofile.io/d/o8N8Kw', 'https://cdn.cloudflare.steamstatic.com/steam/apps/238320/header.jpg', '• İşletim Sistemi: Windows 7 / 10 / 11 64-bit<br>• İşlemci: 2.2 GHz Dual Core Processor<br>• Bellek: 4 GB RAM<br>• Ekran Kartı: 512 MB NVIDIA GeForce 9800GT<br>• Depolama: 5 GB alan', NULL, ARRAY['Korku 💀']::text[], false),
  ('PAYDAY 3', 'FPS / Aksiyon', 'https://gofile.io/d/q9Gfiv', 'https://cdn.cloudflare.steamstatic.com/steam/apps/1272080/header.jpg', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Intel Core i5-10400f / AMD Ryzen 5 3600<br>• Bellek: 16 GB RAM<br>• Ekran Kartı: GTX 1650 (4 GB)<br>• Depolama: 65 GB alan', NULL, ARRAY[]::text[], false),
  ('The Baby in Yellow', 'Korku', 'https://megaup.net/d7dc240914ae60c6e68cc8d204de32f9/The.Baby.In.Yellow.v2025.11.22.rar', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80', '• İşletim Sistemi: Windows 10 64-bit<br>• İşlemci: Quad Core 2.5GHz<br>• Bellek: 4 GB RAM<br>• Ekran Kartı: GTX 750 / Radeon R7 260X<br>• Depolama: 2 GB alan', NULL, ARRAY[]::text[], false)
) as seed(name, category, download_url, cover_url, system_requirements, description, tags, is_cheat)
where not exists (
  select 1 from public.games existing where lower(existing.name) = lower(seed.name)
);

select count(*) as total_games from public.games;
